import { Rubik } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
                <head />
                <body className={rubik.className}>
                    {/* <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                    </ThemeProvider> */}
                        {children}

                </body>
            </html>
        </>
    )
}
