import React from 'react'
import { Rubik } from "next/font/google";
import { cn } from '@/lib/utils';


const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Chat ui",
  description: "Generated by create next app",
};

export default function layer({ children }) {
  return (
    <div className={cn("h-screen bg-verylightgrey", rubik.className)}>{children}</div>
  )
}
